// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace BGuest.Integration.Api.Client
{
    public class PointOfInterestDto
    {
        /// <summary>
        /// Optional. Id
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Optional. Name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Initializes a new instance of the PointOfInterestDto class.
        /// </summary>
        public PointOfInterestDto()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken idValue = inputObject["id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((string)idValue);
                }
                JToken nameValue = inputObject["name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
            }
        }
    }
}
