// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace BGuest.Integration.Api.Client
{
    public class RequestStateModelIntegration
    {
        /// <summary>
        /// Required. Value of state that the Request will change to.
        /// Possible values are: Started: 1; Ready: 2; Completed:
        /// 3; Canceled: -2
        /// </summary>
        public int NewState { get; set; }

        /// <summary>
        /// Initializes a new instance of the RequestStateModelIntegration
        /// class.
        /// </summary>
        public RequestStateModelIntegration()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the RequestStateModelIntegration
        /// class with required arguments.
        /// </summary>
        public RequestStateModelIntegration(int newState)
            : this()
        {
            this.NewState = newState;
        }
        
        ///// <summary>
        ///// Serialize the object
        ///// </summary>
        ///// <returns>
        ///// Returns the json model for the type RequestStateModelIntegration
        ///// </returns>
        //public virtual JToken SerializeJson(JToken outputObject)
        //{
        //    if (outputObject == null)
        //    {
        //        outputObject = new JObject();
        //    }
        //    outputObject["newState"] = this.NewState;
        //    return outputObject;
        //}
    }

    public class CheckInRequestStateModelIntegration
    {
        /// <summary>
        /// Required. Value of state that the Request will change to.
        /// Possible values are: New: 0; Confirmed: 1; Rejected:
        /// -1; Removed: -2
        /// </summary>
        public int NewState { get; set; }

        /// <summary>
        /// Initializes a new instance of the RequestStateModelIntegration
        /// class.
        /// </summary>
        public CheckInRequestStateModelIntegration()
        {
        }

        /// <summary>
        /// Initializes a new instance of the RequestStateModelIntegration
        /// class with required arguments.
        /// </summary>
        public CheckInRequestStateModelIntegration(int newState)
            : this()
        {
            this.NewState = newState;
        }

        ///// <summary>
        ///// Serialize the object
        ///// </summary>
        ///// <returns>
        ///// Returns the json model for the type RequestStateModelIntegration
        ///// </returns>
        //public virtual JToken SerializeJson(JToken outputObject)
        //{
        //    if (outputObject == null)
        //    {
        //        outputObject = new JObject();
        //    }
        //    outputObject["newState"] = this.NewState;
        //    return outputObject;
        //}
    }
}
