// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace BGuest.Integration.Api.Client.Models
{
    public partial class RequestProductOptionDto
    {
        private string _alternative;
        
        /// <summary>
        /// Optional. Value of selected Alternative by Guest for this option
        /// </summary>
        public string Alternative
        {
            get { return this._alternative; }
            set { this._alternative = value; }
        }
        
        private int? _alternativeId;
        
        /// <summary>
        /// Optional. AlternativeId of selected alternative
        /// </summary>
        public int? AlternativeId
        {
            get { return this._alternativeId; }
            set { this._alternativeId = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional. RequestProductOptionId
        /// </summary>
        public int? ID
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional. RequestProductOption Name
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private double? _price;
        
        /// <summary>
        /// Optional. Additional price to be added to Product for selecting
        /// this option
        /// </summary>
        public double? Price
        {
            get { return this._price; }
            set { this._price = value; }
        }
        
        private int? _productOptionId;
        
        /// <summary>
        /// Optional. ProductOption Id of RequestProductOption
        /// </summary>
        public int? ProductOptionId
        {
            get { return this._productOptionId; }
            set { this._productOptionId = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the RequestProductOptionDto class.
        /// </summary>
        public RequestProductOptionDto()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken alternativeValue = inputObject["alternative"];
                if (alternativeValue != null && alternativeValue.Type != JTokenType.Null)
                {
                    this.Alternative = ((string)alternativeValue);
                }
                JToken alternativeIdValue = inputObject["alternativeId"];
                if (alternativeIdValue != null && alternativeIdValue.Type != JTokenType.Null)
                {
                    this.AlternativeId = ((int)alternativeIdValue);
                }
                JToken idValue = inputObject["id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.ID = ((int)idValue);
                }
                JToken nameValue = inputObject["name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken priceValue = inputObject["price"];
                if (priceValue != null && priceValue.Type != JTokenType.Null)
                {
                    this.Price = ((double)priceValue);
                }
                JToken productOptionIdValue = inputObject["productOptionId"];
                if (productOptionIdValue != null && productOptionIdValue.Type != JTokenType.Null)
                {
                    this.ProductOptionId = ((int)productOptionIdValue);
                }
            }
        }
    }
}
