// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace BGuest.Integration.Api.Client.Models
{
    public static partial class StayImportModelCollection
    {
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type IList
        /// </returns>
        public static JToken SerializeJson(IList<StayImportModel> stays, JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            JArray iListSequence = null;
            if (stays != null)
            {
                iListSequence = new JArray();
                outputObject = iListSequence;
                foreach (StayImportModel iListItem in stays)
                {
                    if (iListItem != null)
                    {
                        iListSequence.Add(iListItem.SerializeJson(null));
                    }
                }
            }
            return outputObject;
        }
    }
}
