// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace BGuest.Integration.Api.Client.Models
{
    public static partial class StayReservationDtoCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<StayReservationDto> DeserializeJson(JToken inputObject)
        {
            IList<StayReservationDto> deserializedObject = new List<StayReservationDto>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                StayReservationDto stayReservationDto = new StayReservationDto();
                stayReservationDto.DeserializeJson(iListValue);
                deserializedObject.Add(stayReservationDto);
            }
            return deserializedObject;
        }
    }
}
