// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace BGuest.Integration.Api.Client.Models
{
    public static partial class StayImportResultDtoCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<StayImportResultDto> DeserializeJson(JToken inputObject)
        {
            IList<StayImportResultDto> deserializedObject = new List<StayImportResultDto>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                StayImportResultDto stayImportResultDto = new StayImportResultDto();
                stayImportResultDto.DeserializeJson(iListValue);
                deserializedObject.Add(stayImportResultDto);
            }
            return deserializedObject;
        }
    }
}
