// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace BGuest.Integration.Api.Client.Models
{
    /// <summary>
    /// Stay/reservation possible BGuest's states
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum StayStates
    {
        /// <summary>
        /// Stay / reservation is active
        /// </summary>
        Active = 0,
        /// <summary>
        /// Stay / reservation is inactive or canceled for some reason.
        /// </summary>
        Removed = -1
    }

    public partial class StayImportModel
    {
        private bool _allowExpressCheckout;
        
        /// <summary>
        /// Required. True if the guest is allowed to perform express checkout
        /// (not used at this time)
        /// </summary>
        public bool AllowExpressCheckout
        {
            get { return this._allowExpressCheckout; }
            set { this._allowExpressCheckout = value; }
        }
        
        private string _currentBillCurrency;
        
        /// <summary>
        /// Optional. Current bill value currency (not used at this time)
        /// </summary>
        public string CurrentBillCurrency
        {
            get { return this._currentBillCurrency; }
            set { this._currentBillCurrency = value; }
        }
        
        private DateTimeOffset? _currentBillDate;
        
        /// <summary>
        /// Optional. Date when the current bill value was last updated (not
        /// used at this time)
        /// </summary>
        public DateTimeOffset? CurrentBillDate
        {
            get { return this._currentBillDate; }
            set { this._currentBillDate = value; }
        }
        
        private double? _currentBillValue;
        
        /// <summary>
        /// Optional. Current bill value (not used at this time)
        /// </summary>
        public double? CurrentBillValue
        {
            get { return this._currentBillValue; }
            set { this._currentBillValue = value; }
        }
        
        private string _externalKey;
        
        /// <summary>
        /// Required. External system id. Place you stay/reservation ID on this
        /// field.
        /// You can refer to stays/reservations later through this
        /// key or through BGuest ID.
        /// </summary>
        public string ExternalKey
        {
            get { return this._externalKey; }
            set { this._externalKey = value; }
        }
        
        private string _guestEmail;
        
        /// <summary>
        /// Required. Guest email (bguest will try to match with its user list
        /// through this field)
        /// </summary>
        public string GuestEmail
        {
            get { return this._guestEmail; }
            set { this._guestEmail = value; }
        }

        private string _guestFirstName;
        /// <summary>
        /// Guest first name
        /// </summary>      
        public string GuestFirstName {
            get { return this._guestFirstName; }
            set { this._guestFirstName = value; }
        }
        private string _guestLastName;
        /// <summary>
        /// Guest last name
        /// </summary>      
        public string GuestLastName
        {
            get { return this._guestLastName; }
            set { this._guestLastName = value; }
        }
        /// <summary>
        /// External system id. Place your stay/reservation ID on this field. 
        /// You can refer to stays/reservations later through this key or through BGuest ID.
        /// </summary>

        private bool _isBreakfastIncluded;
        
        /// <summary>
        /// Required. Indicated if the breakfast is included on the stay
        /// </summary>
        public bool IsBreakfastIncluded
        {
            get { return this._isBreakfastIncluded; }
            set { this._isBreakfastIncluded = value; }
        }
        
        private bool _isCheckedIn;
        
        /// <summary>
        /// Required. Indicates if the guest is checked in or not
        /// </summary>
        public bool IsCheckedIn
        {
            get { return this._isCheckedIn; }
            set { this._isCheckedIn = value; }
        }
        
        private DateTimeOffset _periodEnd;
        
        /// <summary>
        /// Required. Stay period end date
        /// </summary>
        public DateTimeOffset PeriodEnd
        {
            get { return this._periodEnd; }
            set { this._periodEnd = value; }
        }
        
        private DateTimeOffset _periodStart;
        
        /// <summary>
        /// Required. Stay period start date
        /// </summary>
        public DateTimeOffset PeriodStart
        {
            get { return this._periodStart; }
            set { this._periodStart = value; }
        }
        
        private string _reservation;
        
        /// <summary>
        /// Optional. Reservation code
        /// </summary>
        public string Reservation
        {
            get { return this._reservation; }
            set { this._reservation = value; }
        }
        
        private string _room;
        
        /// <summary>
        /// Optional. Room number
        /// </summary>
        public string Room
        {
            get { return this._room; }
            set { this._room = value; }
        }

        private StayStates _state;
        /// <summary>
        /// Current Stay / reservation state. 
        /// Possible values are Active or Removed.
        /// </summary>
        public StayStates State {
            get { return this._state; }
            set { this._state = value; }
        }

        /// <summary>
        /// Initializes a new instance of the StayImportModel class.
        /// </summary>
        public StayImportModel()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type StayImportModel
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.ExternalKey == null)
            {
                throw new ArgumentNullException("ExternalKey");
            }
            if (this.GuestEmail == null)
            {
                throw new ArgumentNullException("GuestEmail");
            }
            outputObject["allowExpressCheckout"] = this.AllowExpressCheckout;
            if (this.CurrentBillCurrency != null)
            {
                outputObject["currentBillCurrency"] = this.CurrentBillCurrency;
            }
            if (this.CurrentBillDate != null)
            {
                outputObject["currentBillDate"] = this.CurrentBillDate.Value;
            }
            if (this.CurrentBillValue != null)
            {
                outputObject["currentBillValue"] = this.CurrentBillValue.Value;
            }
            if (this.ExternalKey != null)
            {
                outputObject["externalKey"] = this.ExternalKey;
            }
            if (this.GuestEmail != null)
            {
                outputObject["guestEmail"] = this.GuestEmail;
            }
            if (this.GuestFirstName != null)
            {
                outputObject["guestFirstName"] = this.GuestFirstName;
            }
            if (this.GuestLastName != null)
            {
                outputObject["guestLastName"] = this.GuestLastName;
            }
            outputObject["isBreakfastIncluded"] = this.IsBreakfastIncluded;
            outputObject["isCheckedIn"] = this.IsCheckedIn;
            outputObject["periodEnd"] = this.PeriodEnd;
            outputObject["periodStart"] = this.PeriodStart;
            if (this.Reservation != null)
            {
                outputObject["reservation"] = this.Reservation;
            }
            if (this.Room != null)
            {
                outputObject["room"] = this.Room;
            }
            outputObject["state"] = this.State.ToString();
            return outputObject;
        }
    }
}
