// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using Newtonsoft.Json.Linq;

namespace BGuest.Integration.Api.Client.Models
{
    public partial class SubServiceDto
    {
        private string _externalKey;
        
        /// <summary>
        /// Optional. External system key
        /// </summary>
        public string ExternalKey
        {
            get { return this._externalKey; }
            set { this._externalKey = value; }
        }
        
        private string _id;
        
        /// <summary>
        /// Optional. Sub service id
        /// </summary>
        public string ID
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional. Sub service name
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private SubServiceTypeDto _subServiceType;
        
        /// <summary>
        /// Optional. Sub service type
        /// </summary>
        public SubServiceTypeDto SubServiceType
        {
            get { return this._subServiceType; }
            set { this._subServiceType = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the SubServiceDto class.
        /// </summary>
        public SubServiceDto()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken externalKeyValue = inputObject["externalKey"];
                if (externalKeyValue != null && externalKeyValue.Type != JTokenType.Null)
                {
                    this.ExternalKey = ((string)externalKeyValue);
                }
                JToken idValue = inputObject["id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.ID = ((string)idValue);
                }
                JToken nameValue = inputObject["name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken subServiceTypeValue = inputObject["subServiceType"];
                if (subServiceTypeValue != null && subServiceTypeValue.Type != JTokenType.Null)
                {
                    SubServiceTypeDto subServiceTypeDto = new SubServiceTypeDto();
                    subServiceTypeDto.DeserializeJson(subServiceTypeValue);
                    this.SubServiceType = subServiceTypeDto;
                }
            }
        }
    }
}
